version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
       - echo Running npm install 
       - npm install # run npm install to install all dependencies
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Nothing to do in the build phase...
  post_build:
    commands:
      - echo Nothing to do in the post_build phase...
artifacts:
  files:
     - '**/*' #copy all build files to S3 location